import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        indexedDB: 'readonly',
        console: 'readonly',
        URL: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        HTMLVideoElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLElement: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        EventBus: 'readonly',
        FileReader: 'readonly',
        Blob: 'readonly',
        ClipboardItem: 'readonly',
        ResizeObserver: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        getComputedStyle: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        self: 'readonly',
        AbortController: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        sessionStorage: 'readonly',
        NodeFilter: 'readonly',
        XMLSerializer: 'readonly',
        Image: 'readonly',
        DOMParser: 'readonly',
        Notification: 'readonly',
        location: 'readonly',
        history: 'readonly',
        top: 'readonly',
        parent: 'readonly',
        opener: 'readonly',
        fetch: 'readonly',
        structuredClone: 'readonly',
        process: 'readonly',
        import: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-console': 'off',
      'prefer-const': 'warn',
      'no-var': 'error',
      'eqeqeq': ['warn', 'smart'],
      'no-control-regex': 'off',
      'no-useless-escape': 'off',
      'no-empty': 'off',
    },
  },
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'test-results/**',
      '**/*.test.js',
      'scripts/**',
    ],
  },
];
